name: C++ CI with Microsoft Visual Studio 2022

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up msbuild
      uses: microsoft/setup-msbuild@v1.1 # This ensures MSBuild is available

    - name: Build with MSBuild
      run: |
        msbuild "Solution_Maze.sln" /p:Configuration=Release /p:Platform=x64
    - name: Run
      run: |
        .\x64\Release\Console_Maze.exe
