name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    - name: Compile
      run: |
        g++ -o build/maze Console_Maze/Console_Maze.cpp
    - name: Run
      run: ./build/maze
