name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List files recursively
      run: ls -la

    - name: Generate configure script if missing
      run: |
        if [ ! -f ./configure ]; then
          sudo apt-get update
          sudo apt-get install -y autoconf automake
          autoreconf -i
        fi
    
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
